spring.application.name=chat-with-pdf
# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/pdfchat?TimeZone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Optional: reduce noisy Hibernate logs
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.ai.openai.api-key=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
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.chat.options.model=gpt-4o-mini


# Ask Spring AI to create the schema/table and required extensions
spring.ai.vectorstore.pgvector.initialize-schema=true

# Make sure the dimensions match your embedding model
spring.ai.vectorstore.pgvector.dimensions=1536
# OpenAI text-embedding-3-small
# Optional tuning
spring.ai.vectorstore.pgvector.index-type=HNSW
# or IVFFLAT
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
# spring.ai.vectorstore.pgvector.schema-validation=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
